// 'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./globals.module.css";
import Link from "next/link";
import LogoutForm from "./components/LogoutForm";
import NavBar from "./components/NavBar";
import IntroOverlay from "./components/IntroOverlay";
import StarryBackground from "./components/StarryBackground";
import ThreeJsPlanets from "./components/ThreeJsPlanets";
import ScrollRocket from "./components/ScrollRocket";
import ScrollReset from "./components/ScrollReset";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.body}`}>
        <ScrollReset />
        <NavBar styling={styles.navBar} />
        <IntroOverlay/>
        {children}
      </body>
    </html>
  );
}
